<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo Config::get('ident'); ?>'>
	<head>
		<meta charset='utf-8'>
		<title><?php echo Config::get('sitename'); ?></title>
		<?php echo Ajde::app()->getDocument()->getHead('css'); ?>
	</head>
	<body>
		<div id='ajax-wrapper'>						
			<div class="overlay">
				<?php echo Ajde::app()->getDocument()->getBody(); ?>
			</div>
		</div>
		<?php echo Ajde::app()->getDocument()->getScripts(); ?>		
	</body>
</html>